<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-SSCNS1D" ignored="4" name="Default test" tests="1" failures="1" timestamp="2021-08-02T14:35:28 IST" time="20.136" errors="0">
  <testcase name="verifyrecordBill" time="14.328" classname="com.qa.TestCases.DronaBillingTestPage">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.qa.reports.ExtentLogger.pass(ExtentLogger.java:9)
at com.qa.pages.DronaLoginPage.dronaLoginThroghMobileNo(DronaLoginPage.java:82)
at com.qa.TestCases.DronaBillingTestPage.verifyrecordBill(DronaBillingTestPage.java:54)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verifyrecordBill -->
  <testcase name="verifyConsultPageBillGenerate" time="0.0" classname="com.qa.TestCases.DronaBillingTestPage">
    <ignored/>
  </testcase> <!-- verifyConsultPageBillGenerate -->
  <testcase name="verifyNewBillItem" time="0.0" classname="com.qa.TestCases.DronaBillingTestPage">
    <ignored/>
  </testcase> <!-- verifyNewBillItem -->
  <testcase name="verifynewBillCreate" time="0.0" classname="com.qa.TestCases.DronaBillingTestPage">
    <ignored/>
  </testcase> <!-- verifynewBillCreate -->
  <testcase name="verifyBillItemDelete" time="0.0" classname="com.qa.TestCases.DronaBillingTestPage">
    <ignored/>
  </testcase> <!-- verifyBillItemDelete -->
</testsuite> <!-- Default test -->
